interface IComic {
    emotion_normal: string;
    emotion_laugh: string;
    emotion_sad: string;
    emotion_angry: string;
    emotion_worried: string;
    emotion_surprised: string;
    emotion_wink: string;
    pose_pointingright: string;
    pose_pointingup: string;
    pose_yuhoo: string;
    pose_superperfect: string;
    pose_holdinglaptop: string;
    pose_angryfrustrated: string;
    pose_handsfolded: string;
    pose_handsonhip: string;
    pose_holdingbook: string;
    pose_readingpaper: string;
    pose_thumbsup: string;
    pose_thinkinghmm: string;
 }

let comicMappings: { [id: string]: IComic; } = {
    "dey": {
        emotion_normal: "neutral",
        emotion_laugh: "laugh",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "afraid",
        emotion_surprised: "surprised",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "dee": {
        emotion_normal: "neutral",
        emotion_laugh: "laugh",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "surprised",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "handsinpocket",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "bean": {
        emotion_normal: "neutral",
        emotion_laugh: "smile",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "annoyed",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "priya": {
        emotion_normal: "neutral",
        emotion_laugh: "laugh",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "shocked",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "ringo": {
        emotion_normal: "neutral",
        emotion_laugh: "laugh",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "shocked",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "ava": {
        emotion_normal: "normal",
        emotion_laugh: "smile",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "shocked",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    },
    "evan": {
        emotion_normal: "normal",
        emotion_laugh: "smile",
        emotion_sad: "sad",
        emotion_angry: "angry",
        emotion_worried: "worried",
        emotion_surprised: "shocked",
        emotion_wink: "wink",
        pose_pointingright: "pointingright",
        pose_pointingup: "pointingup",
        pose_yuhoo: "yuhoo",
        pose_superperfect: "super",
        pose_holdinglaptop: "holdinglaptop",
        pose_angryfrustrated: "angry",
        pose_handsfolded: "handsfolded",
        pose_handsonhip: "handsonhip",
        pose_holdingbook: "holdingbook",
        pose_readingpaper: "readingpaper",
        pose_thumbsup: "thumbsup",
        pose_thinkinghmm: "thinking"
    }
 };
export default comicMappings;
